
version: '3.8'

services:
  nexus-ai:
    build: .
    container_name: nexus-ai-bot
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./scan:/app/scan
      - ./xmd:/app/xmd
      - ./media:/app/media
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
